In [4]:
import numpy as np 
import math 
import copy 

In [5]:
data = np.load('./data/LR_task_with_antisaccade_synchronised_min.npz')

In [6]:
X = data['EEG']
y = data['labels']

In [7]:
y

array([[  1,   0],
       [  1,   1],
       [  1,   1],
       ...,
       [369,   1],
       [369,   0],
       [369,   0]])

In [8]:
y_backup = copy.deepcopy(y)
y_backup

array([[  1,   0],
       [  1,   1],
       [  1,   1],
       ...,
       [369,   1],
       [369,   0],
       [369,   0]])

In [10]:
new_labels = []
for i in range(len(y)):
    new_labels.append([y[i][0], math.pi if y[i][1] == 0 else 0])

In [11]:
np_labels = np.array(new_labels)
np_labels

array([[  1.        ,   3.14159265],
       [  1.        ,   0.        ],
       [  1.        ,   0.        ],
       ...,
       [369.        ,   0.        ],
       [369.        ,   3.14159265],
       [369.        ,   3.14159265]])

In [12]:
np.savez("./data/Direction_task_with_antisaccade_synchronised_min.npz", EEG=X, labels=np_labels)