In [20]:
import numpy as np
import copy 
import sys
from tqdm import tqdm

In [21]:
tar_pos = [[400, 300],
 [650, 500],
 [400, 100],
 [100, 450],
 [700, 450],
 [100, 500],
 [200, 350],
 [300, 400],
 [100, 150],
 [150, 500],
 [150, 100],
 [700, 100], 
 [300, 200], 
 [100, 100], 
 [700, 500], 
 [500, 400], 
 [600, 250], 
 [650, 100],
 [200, 250],
 [400, 500],
 [700, 150],
 [500, 200],
 [100, 300],
 [700, 300],
 [600, 350],
]

In [22]:
data = np.load('./data/Position_task_with_dots_synchronised_min.npz')
X = data['EEG']
y = data['labels']

In [23]:
y_backup = copy.deepcopy(y)		

In [24]:
y

array([[  1. , 408.1, 315.1],
       [  1. , 640.7, 519.1],
       [  1. , 404.2, 118.8],
       ...,
       [291. , 115.5, 306.1],
       [291. , 732. , 310.3],
       [291. , 632.2, 353.6]])

In [31]:
new_labels = []
text_file = open("./label_log.txt", "w")
for i in tqdm(range(len(y))):
	coord = np.array([y[i][1], y[i][2]])
	min_dist = sys.maxsize
	min_point = None 
	for j in range(len(tar_pos)):
		point = tar_pos[j]
		dist = ((coord - np.array(point))**2).mean()
		if dist < min_dist:
			min_dist = dist
			min_point = j
	label = np.zeros(2)
	label[0] = y[i][0] # participant ID 
	label[1] = min_point

	text_file.write(f"Sample {i}:    coord: {coord}, class: {min_point}, point: {tar_pos[min_point]} \n")

	new_labels.append(label)

text_file.close()

100%|██████████| 35664/35664 [00:28<00:00, 1263.30it/s]


In [32]:
new_labels

[array([1., 0.]),
 array([1., 1.]),
 array([1., 2.]),
 array([1., 3.]),
 array([1., 4.]),
 array([1., 9.]),
 array([1., 6.]),
 array([1., 7.]),
 array([1., 8.]),
 array([1., 9.]),
 array([ 1., 10.]),
 array([ 1., 11.]),
 array([ 1., 12.]),
 array([ 1., 10.]),
 array([ 1., 14.]),
 array([ 1., 15.]),
 array([ 1., 16.]),
 array([ 1., 17.]),
 array([1., 0.]),
 array([ 1., 18.]),
 array([ 1., 19.]),
 array([ 1., 20.]),
 array([ 1., 21.]),
 array([ 1., 22.]),
 array([ 1., 23.]),
 array([ 1., 24.]),
 array([1., 0.]),
 array([1., 0.]),
 array([ 1., 24.]),
 array([ 1., 23.]),
 array([ 1., 22.]),
 array([ 1., 21.]),
 array([ 1., 20.]),
 array([ 1., 19.]),
 array([ 1., 18.]),
 array([1., 0.]),
 array([ 1., 16.]),
 array([ 1., 15.]),
 array([ 1., 14.]),
 array([ 1., 10.]),
 array([ 1., 12.]),
 array([ 1., 11.]),
 array([ 1., 10.]),
 array([1., 9.]),
 array([1., 8.]),
 array([1., 7.]),
 array([1., 6.]),
 array([1., 5.]),
 array([1., 4.]),
 array([1., 3.]),
 array([1., 2.]),
 array([1., 0.]),
 array

In [34]:
np_labels = np.array(new_labels)
np.max(np_labels[:,1])

24.0

In [35]:
np.savez("./data/Dots_Classification_task_with_dots_synchronised_min.npz", EEG=X, labels=np_labels)